
handlers:
- url: /inventory/static
  static_dir: modules/inventory/src/static

- url: /inventory.*
  static_files: modules/inventory/src/index.html
  upload: modules/inventory/src/index.html
  expiration: "15m"
