
handlers:
- url: /inventory/static
  static_dir: modules/inventory/dist/static

- url: /inventory/.*
  static_files: modules/inventory/dist/index.html
  upload: modules/inventory/dist/index.html
  expiration: "15m"

- url: /inventory/
  static_files: modules/inventory/dist/index.html
  upload: modules/inventory/dist/index.html
  expiration: "15m"
